markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
baseurl: http://linkyan.github.com
auto: false
destination: ./_site
title: Link Yan

author_name: Link Yan
author_email: wsyanligang@gmail.com
